CREATE DATABASE BLOG

USE BLOG

CREATE TABLE CATEGORIES 
(
ID INT PRIMARY KEY,
[NAME] NVARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE TAGS
(
ID INT PRIMARY KEY,
[NAME] NVARCHAR (50)NOT NULL UNIQUE
)

CREATE TABLE USERS
(
ID INT PRIMARY KEY,
[NAME] NVARCHAR(50) NOT NULL UNIQUE,
FULLNAME NVARCHAR(50) NOT NULL,
AGE INT CHECK (AGE>= 0 AND AGE<=150)
)

CREATE TABLE COMMENTS
(
ID INT PRIMARY KEY,
CONTENT INT  NOT NULL CHECK (CONTENT >= 0 AND CONTENT <= 250),
USERID INT NOT NULL FOREIGN KEY (USERID) REFERENCES USERS(ID),
BLOGID INT NOT NULL FOREIGN KEY (BLOGID) REFERENCES BLOGS(ID)
 
 )

 CREATE TABLE BLOGS
 (
    ID INT PRIMARY KEY,
    TITLE INT NOT NULL CHECK(TITLE>= 0 AND TITLE <=50),
    DESCRIPTION NVARCHAR(50) NOT NULL,
     USERID INT NOT NULL FOREIGN KEY (USERID) REFERENCES USERS(ID),
     CATEGORYID INT NOT NULL FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES(ID)
)


CREATE TABLE BLOGTAGS 
(
   
    PRIMARY KEY (BLOGID, TAGID),
    BLOGID INT FOREIGN KEY (BLOGID) REFERENCES BLOGS(ID),
    TAGID INT FOREIGN KEY (TAGID) REFERENCES TAGS(ID)
)



CREATE VIEW VW_BLGSWITHUSINFO
as
SELECT  as BLOGTITLE, U.USERNAME, U.FULLNAME
FROM BLOGS B
INNER JOIN 
USERS U ON B.USERID = U.ID







